# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggybank', '0002_auto_20160213_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passbook',
            name='title',
        ),
    ]
